### PR TITLE
group: do not render gap for empty help view

### PR DESCRIPTION
**Pull request by ardnew**
`(*Group).View` renders enabled keybindings in a footer view according to the current `(Field).KeyBinds()`. This footer view is offset vertically by at least one unconditional `(Theme).FieldSeparator`. 

This is fine in most cases as the user will usually have key bindings returned by `(Field).KeyBinds()` for every `Field` – and indeed every package-provided `Field` returns something meaningful when they do.

However, if the user wishes to **not** render this footer view in a custom `Field` (by returning a nil or empty slice from `(Field).KeyBinds()` and using the `KeyMap` directly in `Update`), then the renderer can get confused about the intended output height.

This PR adds a condition on rendering the footer view and its `(Theme).FieldSeparator` gap to ensure they contain more than just white space when combined together.

### CODE REVIEW

**Comment by ardnew** [comment]
Yikes, rebased against the wrong remote. Need to rebase again to squash all these changes.

**Comment by maaslalani** [comment]
Hey @ardnew, let me know if you're able to rebase / open another PR for this one!

**Comment by ardnew** [comment]
Man, I'm having a lot of trouble fixing this headache. I may close this PR and open another one with a much cleaner patch. Is this okay with you? @maaslalani

**Comment by maaslalani** [comment]
Of course! @ardnew

**Comment by ardnew** [comment]
Oh, just re-read your previous comment suggesting I open another PR as an option. I'm gonna take that route. :wink:

**Pull request closed without merging**
