### PR TITLE
fix(multiselect): check if is filterable before enable filtering

### LINKED ISSUE #251: MultiSelect's filterable set to "false" will have no effect.
**Describe the bug**
MultiSelect's filterable set to "false" will have no effect.

**To Reproduce**

1. run a following code:
```go
package main

import (
	"github.com/charmbracelet/huh"
)

func main() {
	var types []string

	form := huh.NewMultiSelect[string]().
		Filterable(false).
		Options(
			huh.NewOption("Module", "Module").Selected(true),
			huh.NewOption("Constant", "Constant").Selected(true),
			huh.NewOption("Method", "Method").Selected(true),
			huh.NewOption("Attribute", "Attribute"),
			huh.NewOption("Class", "Class").Selected(true),
		).
		Title("Types").
		Value(&types)

	huh.NewForm(huh.NewGroup(form)).Run()

}

```
2. Click on "/"
3. Provide a "constant" value

**Expected behavior**
Filtering should not be possible on a MultiSelect field because `Filterable(false)` method was used.

**Desktop (please complete the following information):**
 - OS: Manjaro/Linux
 - Version github.com/charmbracelet/huh v0.4.2, go 1.22

### PR DESCRIPTION
**Pull request by MikaelFangel**
Fixes #251 

### Changes: 
 - Check if the multi select is filterable before changing the state to filtering.
 - Update the test accordingly to the change

### CODE REVIEW

**Comment by maaslalani** [comment]
We should actually simply disable the keybinding so it doesn't show up in the help, disabling it will also prevent this switch from activating.

**Comment by MikaelFangel** [comment]
I noticed by that this will default to disable filterable should we and thus making this a breaking change. Should I add a line enabling filterable per default?

**Comment by skatkov** [comment]
Awesome fix, looking forward for this to get merged ;-)

**Comment by caarlos0** [comment]
> @maaslalani - I noticed by this it will default to disable filterable and thus making this a breaking change. Should we add a line enabling filterable per default?

i think so yeah... can probably do it in `New`

**Comment by caarlos0** [comment]
done in https://github.com/charmbracelet/huh/pull/335/files

**Pull request closed without merging**
