### PR TITLE
feat: select onchange

### PR DESCRIPTION
**Pull request by caarlos0**
The idea is to allow one select to depend on another, e.g., filtering country, then states within that country, then cities within that state.

This is just a raw idea to get your opinions on it, so no tests or anything yet.

### CODE REVIEW

**Comment by maaslalani** [comment]
Personally, I think we should go for a more declarative approach.

Perhaps allowing the options to be passed an `OptionsFunc` (and maybe allowing it to specify dependencies, i.e. which values change).

**Comment by maaslalani** [comment]
So for the `Country / State` example maybe it would be something like:

```
var country string

huh.NewSelect[string]().Title("Country").Options(...)

huh.NewSelect[string]().Title("State").OptionsFunc(..., &country)
```

**Comment by caarlos0** [comment]
That wouldn't be the same though, as `country` would only change when the select is confirmed, not while "browsing", e.g.:

CleanShot 2024-02-12 at 10 43 20

**Comment by maaslalani** [comment]
Taking the `OptionsFunc` declarative route here:
This will support API calls and handle caching for the user as well.

* #69

**Pull request closed without merging**
