### PR TITLE
docs(example): simple example showing conditional options

### PR DESCRIPTION
**Pull request by meowgorithm**
How we might go about officially something like this is a larger topic, but for now here's an example on how one can get started with forms that change based on user choices.

### CODE REVIEW

**Comment by safaci2000** [comment]
Thank you for this, it's almost exactly what I was looking for.  Would also love a way to integrate multiple forms with bubble tea.  I tried to have an array of forms to have dynamic form behavior and was not able to get it working properly.

**Comment by meowgorithm** [comment]
> Thank you for this, it's almost exactly what I was looking for. Would also love a way to integrate multiple forms with bubble tea. I tried to have an array of forms to have dynamic form behavior and was not able to get it working properly.

Totally possible. If you want to open a discussion in the meantime with some (simple) source code would be happy to offer some help.

**Comment by meowgorithm** [comment]
Note: this PR should be refactored to use @caarlos0’s excellent `HideFunc`.

**Comment by maaslalani** [comment]
@meowgorithm, refactored this PR to use `WithHideFunc` makes it so the user can go back and make a different selection which is great!

**Pull request merged**
