### PR TITLE
bugfix/init files when currentdirectory is set

### PR DESCRIPTION
**Pull request by shedyfreak**
I reuse go-gorm PR guidelines, intellectual property goes to the team maintaining the project

[x] Do only one thing
[x] Non breaking API changes
[x] Tested

Scenario 

``` go
                   item := huh.NewFilePicker().
				Title("Select a file:").
				Description("This will be your profile image.").
				AllowedTypes([]string{".pdf", ".docx", ".xlsx", ".gif"}).
				Value(&myModel.Value)
item.CurrentDirectory("random/path/")
```
Here as you might have seen I m creating a FilePicker, and I am trying to read a directory

What's acutally happening
CurrentDirectory and files within the FilePicker are already set to working directory (".")
in huh/field_filepicker.go line 50-52
using Init() when setting CurrentDirectory is set will give the desired behaviour 

alternatively here is a PR to improve the comment over CurrentDirectory function
https://github.com/charmbracelet/huh/pull/229

even though it's not straight forward how to do that 

here is how I did it, please let me know if there is an easier way or I got something wrong

```go
                if cmd := item.Init(); cmd != nil {
				model, _ := item.Update(cmd())
				item = model.(*huh.FilePicker)
			}
```

### CODE REVIEW

**Comment by shedyfreak** [comment]
Thank you for your review, for the failing test it seems something went wrong with context and it's not relevant for the PR

**Comment by maaslalani** [comment]
Please rebase on main if possible! Thank you

**Comment by shedyfreak** [comment]
PR updated with main

**Comment by maaslalani** [comment]
Thanks so much @shedyfreak!

**Pull request merged**
